# File: netlify.toml

[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions/"
  publish = "static/" # Or "templates/" if you prefer

[[redirects]]
  from = ""
  to = "/.netlify/functions/api/:splat"
  status = 200